services:
    game:
        build: 
          context: ./
          dockerfile: ./app/backend/Dockerfile
        ports:
          - "8080"
    languages:
        build:
          context: ./
          dockerfile: ./app/languages/Dockerfile
        ports:
          - "8000"
        # expose:
        #   - "8000"

